%MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
%MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
%MMMM           MMMM           MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
%MMMM           MMMM           MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
%MMMMMMM\     \MMMMMM/     /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
%MMMMMMMM\     \MMMM/     /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
%MMMMMMMMM\     \MM/     /MMMMMMMM/-´´´-\MMMMMMMM        W/        \MMMMMMM
%MMMMMMMMMM\     \/     /MMMMM/`           `\MMMM                   \MMMMMM
%MMMMMMMMMMM\          /MMMMM`     -+o+-     `MMMMMM       -++-      \MMMMM
%MMMMMMMMMMMM\        /MMMMM`     oMMMMMo     `MMMMM      oMMMMo      MMMMM
%MMMMMMMMMMMMM|      |MMMMMM      MMMMMMM      MMMMM     +MMMMMM+     MMMMM
%MMMMMMMMMMMMM|      |MMMMMM      MMMMMMM      MMMMM     +MMMMMM+     MMMMM
%MMMMMMMMMMMMM|      |MMMMMM.     oMMMMMo     .MMMMM      oMMMMo     /MMMMM
%MMMMMMMMMM              MMMM.     -+o+-     .MMMMMM       -++-     /MMMMMM
%MMMMMMMMMM              MMMMMo.           .oMMMMMMM     A         /MMMMMMM
%MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMho\-...-/sdMMMMMMMMM     M\----/MMMMMMMMMMM
%MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM     MMMMMMMMMMMMMMMMMM
%MMMMM A MATLAB TOOLBOX FOR OPTIMAL CONTROL MMMMMMMM     MMMMMMMMMMMMMMMMMM
%MMMMM © (2022) Viktor Leek, Lars Eriksson  MMMM             MMMMMMMMMMMMMM
%MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM             MMMMMMMMMMMMMM
%MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
%MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% 
% - Getting started -
% installation
% 
% - Basic usage -
% yops ...
% ocp ...
% ivp ...
% 
% More details and contact information is found at
% https://www.yoptimalcontrol.com/
% 
% Should you have any questions, comments or opinions on Yop, please
% contact us. Especially important if you are experiencing problems, don't
% know how to formulate a problem, or need a feature that does not yet
% exist.
% 
% Best regards,
% Viktor Leek and Lars Eriksson
yop.logo