t0 = yop.time0;
tf = yop.timef;
t = yop.time;
x = yop.state();
expr = x + 1;

clc

expr(t0);
expr(tf);
expr(t);
expr(t == t0);
expr(t == tf);
expr(t == 2);
expr(t0 == t);
expr(tf == t);
expr(2 == t);
expr(t <= t0);
expr(t <= tf);
expr(t <= 2);
expr(t0 <= t);
expr(tf <= t);
expr(2 <= t);
expr(t >= t0);
expr(t >= tf);
expr(t >= 2);
expr(t0 >= t);
expr(tf >= t);
expr(2 >= t);
expr(t0 <= t <= t0);
expr(t0 <= t <= tf);
expr(tf <= t <= tf);
expr(2  <= t <= tf);
expr(t0 <= t <= 2);
expr(2 <= t <= 3);
expr(t0 >= t >= t0);
expr(tf >= t >= t0);
expr(2 >= t >= t0);
expr(tf >= t >= tf);
expr(tf >= t >= 2);
expr(3 >= t >= 2);