function [dX, signals, constraints, param]=liu_diesel_2(X, U, N_ice, param)
% LIU_DIESEL_2(X, U, N_ice, param)
% -------------------------------------------------------------------------
% LiU Diesel 2 - A MVEM of a CI, 6 cylinder in-line, 2500 Nm, 450 bhp delse
% engine.
% [dX, constraints, signals] = liu_diesel_2(X, U, N_ice, param)
% x = [p_caf, p_im, p_em, n_turb, N_ice]'
% u = [Ne, u_delta, u_thr, u_wg]'
% -------------------------------------------------------------------------

%% States -----------------------------------------------------------------
p_c   = X(1); % Pressure after compressor        [Pa]
p_im  = X(2); % Intake manifold pressure       [Pa]
p_em  = X(3); % Exhaust manifold pressure      [Pa]
w_tc  = X(4); % Turbocharger rotational speed [rad/s]

%% Control signals --------------------------------------------------------
u_f   = U(1); % Fuel injection      [mg/cycle]
u_thr = U(2); % Throttle position   [0, 1]
u_wg  = U(3); % Wastegate position  [0, 1]

%% Unit conversions -------------------------------------------------------
N_tc = w_tc*30/pi; % Turbocharger speed [rpm]
W_f  = (1e-6/60).*u_f.*N_ice.*param.n_cyl./param.n_r; %Fuel massflow [kg/s]

%% Compressor -------------------------------------------------------------
[W_c, eta_c, T_c, P_c, c_constr] ... [kg/s, -, K, W, -]
     = compressor(param.p_amb, p_c, param.T_amb, w_tc, param.comp);

%% Intake manifold --------------------------------------------------------
W_cyl   = W_cylinder(p_im, param.T_im, N_ice, param); % [kg/s]

%% Cylinder ---------------------------------------------------------------
phi   = param.AFs * W_f ./ W_cyl; % Fuel-to-air equivalence ratio [-] 
% phi = param.AFs * u_f * 1e-6 * param.R_a * param.T_im /( param.n_cyl * p_im * param.V_D * param.eta_vol);
[M_ice, cyl_sig] = engine_torque(N_ice, p_im, p_em, u_f, phi, param); %[Nm]
[T_em, T_e]  = T_em_model(p_im, p_em, param.T_im, W_f, W_cyl, param); % [K]

%% Throttle ---------------------------------------------------------------
[W_thr, ~, Pi_thr] = W_throttle(p_c, p_im, param.T_cac, u_thr, param);

%% Turbine ----------------------------------------------------------------
N_tc_corr  = N_tc./sqrt(T_em);  % [rpm/(T_em^0.5)]
Pi_t       = param.p_ats./p_em; % [-]
W_t_corr   = turbine_massflow(Pi_t, N_tc_corr, param); % [kg/s*kPa*K^-0.5]
W_t        = W_t_corr.* p_em./1e3./sqrt(T_em);         % [kg/s]
BSR        = turbine_BSR(Pi_t, w_tc, T_em, param);     % [-]
[eta_tm, BSR_opt] = turbine_efficiency(BSR, N_tc_corr, param);% [-]
P_t_eta_tm = turbine_power(W_t, T_em, Pi_t, eta_tm, param); % [W]
T_t        = turbine_outlet_temperature(T_em, eta_tm, Pi_t, param); % [K]

%% Wastegate --------------------------------------------------------------
W_wg      = W_wastegate(p_em, param.p_ats, T_em, u_wg, param); % [kg/s]

%% Temperature mix after turbine ------------------------------------------
T_eats = T_exhaust_mix(T_t,T_em,W_t,W_wg); % [K]

%% Dynamics ---------------------------------------------------------------
dp_c = param.R_a .* T_c .* (W_c - W_thr) ./ param.V_c;
dpim  = param.R_a .* param.T_im .* (W_thr - W_cyl) ./ param.V_im;
dpem  = param.R_e .* T_em .* (W_cyl + W_f - W_t - W_wg) ./ param.V_em;
dwtc  = (P_t_eta_tm - P_c) ./ (w_tc .* param.J_tc);
dX    = [dp_c; dpim; dpem; dwtc];

%% Constraints ------------------------------------------------------------
% Constraint 1: Torque limit 500 -1000 rpm
% Constraint 2: Torque limit 1000-1300 rpm
% Constraint 3: Torque limit 1300-1900 rpm
% Constraint 4: Torque limit 1900-2400 rpm
% Constraint 5: Turbine minimum efficiency
% Constraint 6: Smoke limiter
% Constraint 7: Compressor constraints
constraints = [...
 ...M_ice-100*(param.constr.M_max1(1) + param.constr.M_max1(2)*( ...
 ...          (N_ice-param.constr.M_max1(3))/1000).^2 );...
 ...M_ice-2400;... 
 ...M_ice-100*(param.constr.M_max2(1) + param.constr.M_max2(2)*N_ice/1000);...
 ...M_ice-100*(param.constr.M_max3(1) + param.constr.M_max3(2)*N_ice/1000);...
 .01 - eta_tm;...
 ...(phi-1/param.constr.lambda_min);...
 .01 - eta_c;...
 p_im-p_c;...
 10000*pi/30-w_tc;...
 -W_cyl;...
 -W_t;...
 -W_wg;...
 c_constr];

%% Signals ----------------------------------------------------------------
signals=struct(...
    'eta', (M_ice.*N_ice*pi/30)/(W_f*param.q_HV), ...
    'dBSR', BSR-BSR_opt, ...
    ... Compressor and Throttle
    'p_c'   ,p_c  , ...
    'W_thr'   ,W_thr  , ...
    'u_thr'   ,u_thr  , ...
    'Pi_thr'  ,Pi_thr , ...
    ... Intake manifold
    'p_im'    ,p_im   , ...
    'W_cyl'   ,W_cyl  , ...
    ... Cylinder
    'N_ice'   ,N_ice  , ...
    'M_ice'   ,M_ice  , ...
    'P_ice'   ,M_ice.*N_ice*pi/30  , ...
    'u_f'     ,u_f    , ...
    'W_f'     ,W_f    , ...
    'Lambda'  ,1./phi , ...
    'phi'     ,phi    , ...
    'M_fric'  ,cyl_sig.M_fric, ...
    'M_pump'  ,cyl_sig.M_pump, ...
    'M_ig'    ,cyl_sig.M_ig, ...
    'BMEP'    ,cyl_sig.BMEP, ...
    'IMEP'    ,cyl_sig.IMEP, ...
    'PMEP'    ,cyl_sig.PMEP, ...
    'FMEP'    ,cyl_sig.FMEP, ...
    'gamma_cyl',cyl_sig.gamma, ...
    'eta_otto' ,cyl_sig.eta_otto, ...
    'eta_inj' ,cyl_sig.eta_cal, ...
    'eta_ig' ,cyl_sig.eta_ig, ...
    ... Exhaust manifold
    'p_em'    ,p_em   , ...
    'T_em'    ,T_em   , ...
    'T_e'     ,T_e    , ...
    ... Turbo
    'w_t'     ,w_tc    , ...
    'N_t'     ,w_tc*30/pi, ... [rpm]
    'eta_tm'  ,eta_tm , ...
    ... Turbine
    'Pi_t'    ,Pi_t   , ...
    'W_wg'    ,W_wg   , ...
    'u_wg'    ,u_wg   , ...
    'W_t'     ,W_t    , ...
    'BSR'     ,BSR    , ...
    'T_turb'  ,T_t    , ...
    'T_exhaust' ,T_eats, ...
    'P_turb_eta_tm', P_t_eta_tm, ...
    'W_delta', W_t+W_wg-W_f, ...
    ... Compressor
    'Pi_c' ,p_c./param.p_amb  , ...
    'W_c'  ,W_c   , ...
    'eta_c',eta_c , ...
    'T_c'  ,T_c   , ...
    'P_c'  ,P_c     ...
    );
end