function logo()
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMM           MMMM           MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMM           MMMM           MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMM\\     \\MMMMMM/     /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMM\\     \\MMMM/     /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMM\\     \\MM/     /MMMMMMMM/-´´´-\\MMMMMMMM        W/        \\MMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMM\\     \\/     /MMMMM/`           `\\MMMM                   \\MMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMM\\          /MMMMM`     -+o+-     `MMMMMM       /oo\\      \\MMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMM\\        /MMMMM`     oMMMMMo     `MMMMM      oMMMMo      MMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMM|      |MMMMMM      MMMMMMM      MMMMM     +MMMMMM+     MMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMM|      |MMMMMM      MMMMMMM      MMMMM     +MMMMMM+     MMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMM|      |MMMMMM.     oMMMMMo     .MMMMM      oMMMMo     /MMMMMMMM\n');
fprintf('MMMMMMMMMMMMM              MMMM.     -+o+-     .MMMMMM       \\oo/     /MMMMMMMMM\n');
fprintf('MMMMMMMMMMMMM              MMMMMo.           .oMMMMMMM     A         /MMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMM              MMMMMMMho\\-...-/sdMMMMMMMMM     M\\----/MMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM     MMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM     MMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM             MMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM             MMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
end