function logo()
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMNmmmmmmmmmmmmNMMNmmmmmmmmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMy............-MM+...........mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMs            `MM/           mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMmyyy-      .syMMdy+     /yyyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMN+      /NMMMy`   `sMMMMMMMNmmmmmNMMMMMMMMNNNNNNNNMMMMNmmNMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMy`     :mMo    .hMMMMMms/-.```.-/smMMMMm--------ydo:....:+dMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMm-     ./    :mMMMMm/`           `+mMMm        .          /mMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMN+         oMMMMMh`    `+yhy/     .dMNyy:      `/oo/`     -NMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMh       hMMMMMN`     dMMMMMs     -MMMMo     .mMMMMN-     oMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMM`      MMMMMMh     .MMMMMMM      mMMMo     sMMMMMMy     -MMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMM`      MMMMMMh     .MMMMMMN      NMMMo     sMMMMMMs     -MMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMM`      MMMMMMM.     oMMMMM/     :MMMMo     `dMMMMm.     oMMMMMMM\n');
fprintf('MMMMMMMMMMMMo///       ///oMMMm.     -+o+.     :NMMMMo       -++:`     -NMMMMMMM\n');
fprintf('MMMMMMMMMMMM:             :MMMMNo.           -yNMMMMMo     .         `+NMMMMMMMM\n');
fprintf('MMMMMMMMMMMMo/////////////oMMMMMMNho/----:/sdNMMMMMMMo     odo/----/smMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNMMMMMMMMMMMo     sMMMNNNNMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhh/     +hhhMMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/            NMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+............NMMMMMMMMMMMMMMMM\n');
fprintf('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n');
end