% Debugging using syms
syms tt xx1 xx2 xx3 uu
xx = [xx1; xx2; xx3];

import yop.*
t = ast_variable();
x = ast_variable([3, 1]);
u = ast_variable();
[dx, y] = rocket_model(x, u);
rocket = y.rocket;

ocp = yop.ocp();
ocp.max(rocket.height);
ocp.st(...
    t0  == 0, tf >= 0, ...
    der(x) == rocket_model(x, u), ...
    rocket.height >= 0, ...
    rocket.velocity >= 0, ...
    68 <= rocket.mass <= 215, ...
     0 <= rocket.fuel_mass_flow <= 9.5 ...
    );

x.value = xx;
u.value = uu;

%%
import yop.*
[t, t0, tf] = independent('t');
x = state('x', 3);
u = control('u');

[dx, y] = rocket_model(x, u);

ocp = yop.ocp();
ocp.max(y.rocket.height);
ocp.st(...
    t0  == 0, ...
    tf >= 0, ...
    der(x) == rocket_model(x, u), ...
    y.rocket.height >= 0, ...
    y.rocket.velocity >= 0, ...
    68 <= y.rocket.mass <= 215, ...
     0 <= y.rocket.fuel_mass_flow <= 9.5 ...
    );

% rocket.height(t0);
% rocket.height(tf);
% rocket.height(t==4);