%% Stiff ODE - Van der Pol equations in relaxation oscillation
%   https://se.mathworks.com/help/matlab/ref/ode15s.html
yopvar t t0 tf x1 x2
x = [x1; x2];
sol = yop.simulation(...
    t0==0, tf==3000, ...
    der(x) == [x2; 1000*(1 - x1^2)*x2 - x1], ...
    x(t0) == [2; 0] ...
    ).solve('solver', 'cvodes', 'points', 3000);
sol.plot(t, x1)