clear all;

t0 = yop.time0();
tf = yop.timef();
t = yop.time();
x = yop.state([6, 1]);
u = yop.control([2, 1], 'pw', 'quadratic');
p = yop.parameter();

x_max = [+1000; +1000; 1000; 350; +75*pi/180; +0.5*pi];
x_min = [-1000; -1000;    0;  10; -75*pi/180; -3.0*pi];

u_max = [+1.5; +75*pi/180];
u_min = [-0.5; -75*pi/180];

p_max = 0.15;
p_min = 0.005;

[dx, y] = soaring(x, u, p);

ivp = yop.ivp( ...
    t0==0, tf==30, ...
    der(x) == dx, ...
         p == 0.08, ...
     x(t0) == [0; 0; 0; 220; 0; -1], ...
         u == [0.3 + 0.5*sin(0.1*t); (-40 + 10*sin(0.55*t))*pi/180]  ... u == [0.3; -1] ...
    );
sim = ivp.solve();
%%
% sim.plot3(x(1), x(2), x(3))
% sim.plot(t, 0.3 + 0.5*sin(0.1*t))

%%
ocp = yop.ocp('Dynamic Soaring Problem');
% ocp.min( p + ddu(1)^2 + ddu(2)^2 );
ocp.min( p );
ocp.st( ...
    1 <= tf <= 30, ...
    der(x) == dx, ...
    x_min <= x <= x_max, ...
    u_min <= u <= u_max, ...
    p_min <= p <= p_max, ...
    x(1:3).at(t0) == 0, ...
    x(1:3).at(tf) == 0, ...
    x(4:5).at(t0) == x(4:5).at(tf), ...
    x(6).at(t0) == x(6).at(tf) + 2*pi, ...
    der(x(6)) <= 0 ...
    );
sol = ocp.solve('intervals', 50, 'degree', 5, 'guess', sim);
% sol = ocp.solve('intervals', 100, 'degree', 4, 'guess', sol);

%%
ocp = yop.ocp('Dynamic Soaring Problem');
ocp.min( p );
ocp.st( ...
    1 <= tf <= 30, ...
    der(x) == dx, ...
    x_min <= x <= x_max, ...
    u_min <= u <= u_max, ...
    p_min <= p <= p_max, ...
    x(1:3).at(t0) == 0, ...
    x(1:3).at(tf) == 0, ...
    x(4:5).at(t0) == x(4:5).at(tf), ...
    x(6).at(t0) == x(6).at(tf) + 2*pi, ...
    der(x(6)) <= 0 ...
    );
sol = ocp.solve('intervals', 50, 'degree', 4, 'guess', sol);

%%
% sol.plot3(x(1), x(2), x(3))
% sol.plot(t, u(1))
sol.plot(t, x(4))
